name: Build on Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Install dependencies (go mod tidy)
      run: go mod tidy
    - name: Build
      run: go build
    - name: Test
      run: go test -json > TestResults.json
